"""
Defines the default settings used to configure the RFM9x satellite
"""

CHECKSUM = True
TX_POWER = 23
BITRATE = 2400
FREQUENCY_DEVIATION = 10000
RX_BANDWIDTH = 25.0
PREAMBLE_LENGTH = 16
ACK_DELAY = 1.0
ACK_WAIT = 5

SATELLITE_ID = 0xAB
GROUNDSTATION_ID = 0xBA
