DEFAULT = 0x00

MEMORY_BUFFERED_START = 0xff
MEMORY_BUFFERED_MID = 0xfe
MEMORY_BUFFERED_END = 0xfd

DISK_BUFFERED_START = 0xfc
DISK_BUFFERED_MID = 0xfb
DISK_BUFFERED_END = 0xfa

COMMAND = 0x01

BEACON = 0x02
